from management.models import Profile
from django import forms
from .models import Product


class  Product_forms(forms.ModelForm):
    # product_vender=forms.InlineForeignKeyField(profile=request.user)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)        
        self.fields["product_vendor"].widget.attrs.update({
            'name':'product_vendor',
            'id':'product_vendor',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'product_vendor',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["product_name"].widget.attrs.update({
            'name':'product_name',
            'id':'product_name',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'product_name',
            'maxlength':'50',
            'minlength':'6'
        })
        
        self.fields["product_description"].widget.attrs.update({
            'name':'product_description',
            'id':'product_description',
            'style':'height:150px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'product_description',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["product_image"].widget.attrs.update({
            'name':'product_image',
            'id':'product_image',
            'style':'height:40px',
            # 'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'product_image',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["product_minicategor"].widget.attrs.update({
            'name':'product_minicategor',
            'id':'product_minicategor',
            'style':'height:40px',
            # 'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'product_minicategor',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["product_subcategory"].widget.attrs.update({
            'name':'product_subcategory',
            'id':'product_subcategory',
            'style':'height:40px',
            # 'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'product_subcategory',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["product_maincategory"].widget.attrs.update({
            'name':'product_maincategory',
            'id':'product_maincategory',
            'style':'height:40px',
            # 'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'product_maincategory',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["product_supercategory"].widget.attrs.update({
            'name':'product_supercategory',
            'id':'product_supercategory',
            'style':'height:40px',
            # 'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'product_supercategory',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["content"].widget.attrs.update({
            'name':'content',
            'id':'content',
            'style':'height:80px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'content',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["PRDPrice"].widget.attrs.update({
            'name':'PRDPrice',
            'id':'PRDPrice',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'PRDPrice',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["PRDDiscountPrice"].widget.attrs.update({
            'name':'PRDDiscountPrice',
            'id':'PRDDiscountPrice',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'PRDDiscountPrice',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["additional_image_1"].widget.attrs.update({
            'name':'additional_image_1',
            'id':'additional_image_1',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'additional_image_1',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["additional_image_2"].widget.attrs.update({
            'name':'additional_image_2',
            'id':'additional_image_2',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'additional_image_2',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["additional_image_3"].widget.attrs.update({
            'name':'additional_image_3',
            'id':'additional_image_3',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'additional_image_3',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["additional_image_4"].widget.attrs.update({
            'name':'additional_image_4',
            'id':'additional_image_4',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'additional_image_4',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["width"].widget.attrs.update({
            'name':'width',
            'id':'width',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'width',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["height"].widget.attrs.update({
            'name':'height',
            'id':'height',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'height',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["PRDWeight"].widget.attrs.update({
            'name':'PRDWeight',
            'id':'PRDWeight',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'PRDWeight',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["pieces"].widget.attrs.update({
            'name':'pieces',
            'id':'pieces',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'pieces',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["available"].widget.attrs.update({
            'name':'available',
            'id':'available',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'available',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["promotional"].widget.attrs.update({
            'name':'promotional',
            'id':'promotional',
            'style':'height:40px',
            # 'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'promotional',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["PRDISactive"].widget.attrs.update({
            'name':'PRDISactive',
            'id':'PRDISactive',
            'style':'height:40px',
            # 'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'PRDISactive',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["PRDSKU"].widget.attrs.update({
            'name':'PRDSKU',
            'id':'PRDSKU',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'PRDSKU',
            'maxlength':'50',
            'minlength':'6'
        })
    class Meta:
        model=Product
        fields=['product_vendor','product_name','product_description','product_image',
        'product_minicategor','product_subcategory','product_maincategory','product_supercategory',
        'content','PRDPrice','PRDDiscountPrice','additional_image_1','additional_image_2',
        'additional_image_3','additional_image_4','width','height','PRDWeight','pieces','available',
        'promotional','PRDISactive','PRDSKU']

from .models import Payment


class PaymentForm(forms.ModelForm): 
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)        
        self.fields["first_name"].widget.attrs.update({
            'name':'first_name',
            'id':'first_name',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'first_name',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["last_name"].widget.attrs.update({
            'name':'last_name',
            'id':'last_name',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'last_name',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["state"].widget.attrs.update({
            'name':'state',
            'id':'state',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'state',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["street_address"].widget.attrs.update({
            'name':'street_address',
            'id':'street_address',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'street_address',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["post_code"].widget.attrs.update({
            'name':'post_code',
            'id':'post_code',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'post_code',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["City"].widget.attrs.update({
            'name':'City',
            'id':'City',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'City',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["Email_Address"].widget.attrs.update({
            'name':'Email_Address',
            'id':'Email_Address',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'Email_Address',
            'maxlength':'50',
            'minlength':'6'
        })
        self.fields["phone"].widget.attrs.update({
            'name':'phone',
            'id':'phone',
            'style':'height:40px',
            'size':'50px',
            'type':'text',
            'class':'form-control',
            'placeholder':'phone',
            'maxlength':'50',
            'minlength':'6'
        })
    class Meta:
        model=Payment
        fields=[
            'first_name','last_name','state','street_address','post_code','City','Email_Address','phone'
        ]       