# Generated by Django 3.1.2 on 2022-10-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=100, null=True)),
                ('site_title', models.CharField(blank=True, max_length=100, null=True)),
                ('site_discription', models.CharField(blank=True, max_length=500, null=True)),
                ('site_address', models.CharField(blank=True, max_length=200, null=True)),
                ('site_url', models.URLField(blank=True, null=True)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='sites/images')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='sites/images')),
                ('site_form_image', models.ImageField(blank=True, null=True, upload_to='sites/images')),
                ('site_contect_no1', models.CharField(blank=True, max_length=20, null=True)),
                ('site_contect_no2', models.CharField(blank=True, max_length=20, null=True)),
                ('site_work_time', models.CharField(blank=True, max_length=100, null=True)),
                ('site_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_facebook', models.URLField(blank=True, null=True)),
                ('site_instagram', models.URLField(blank=True, null=True)),
                ('site_twitter', models.URLField(blank=True, null=True)),
                ('site_youtube', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
